Dapeda/Controllers/CategoryController.cs
using Dapeda.Models;
using Microsoft.AspNetCore.Mvc;
using Dapper;
using System.Data;

public class CategoryController : Controller
{

    public IActionResult Index(string searchTerm)
    {
        IEnumerable<Category> categories;

        if (!string.IsNullOrWhiteSpace(searchTerm))
        {
            var param = new DynamicParameters();
            param.Add("@SearchTerm", searchTerm);
            categories = DP.Listeleme<Category>("sp_SearchCategoriesByName", param);
        }
        else
        {
            categories = DP.Listeleme<Category>("sp_GetCategories");
        }

        if (!categories.Any() && !string.IsNullOrWhiteSpace(searchTerm))
        {
            ViewBag.Mesaj = "Arama kriterlerine uygun kategori bulunamadı.";
        }

        return View(categories);
    }

    public IActionResult AddCategory()
    {
        return View();
    }


    [HttpPost]
    public IActionResult AddCategory(Category model)
    {
        if (ModelState.IsValid)
        {
            var param = new DynamicParameters();
            param.Add("@CategoryName", model.CategoryName);

            DP.ExecuteReturn("sp_AddCategory", param);
            return RedirectToAction("Index");
        }
        return View(model);
    }


    public IActionResult EditCategory(int id)
    {
        var param = new DynamicParameters();
        param.Add("@CategoryId", id);

        var category = DP.GetSingle<Category>("sp_GetCategoryById", param);
        if (category == null) return NotFound();

        return View(category);
    }

  
    [HttpPost]
    public IActionResult EditCategory(Category model)
    {
        if (ModelState.IsValid)
        {
            var param = new DynamicParameters();
            param.Add("@CategoryId", model.CategoryId);
            param.Add("@CategoryName", model.CategoryName);

            DP.ExecuteReturn("sp_UpdateCategory", param);
            return RedirectToAction("Index");
        }
        return View(model);
    }


    public IActionResult DeleteCategory(int id)
    {
        var param = new DynamicParameters();
        param.Add("@CategoryId", id);

        var category = DP.GetSingle<Category>("sp_GetCategoryById", param);
        if (category == null) return NotFound();

        return View(category);
    }


    [HttpPost]
    public IActionResult DeleteCategoryConfirmed(int CategoryId)
    {
        var param = new DynamicParameters();
        param.Add("@CategoryId", CategoryId);

        DP.ExecuteReturn("sp_DeleteCategory", param);
        return RedirectToAction("Index");
    }

    public ActionResult ProductWithCategory()
    {
        var products = DP.Listeleme<ProductWithCategory>("sp_GetProducts").ToList();
        return View(products);
    }


    public IActionResult CategoryPriceReport()
    {
        var model = GetAveragePriceByCategory();
        return View(model);
    }

    public IEnumerable<CategoryPriceSummary> GetAveragePriceByCategory()
    {
        return DP.Listeleme<CategoryPriceSummary>("sp_GetAveragePriceByCategory");
    }



}

Dapeda/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Dapper;
using Dapeda.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

public class OrderController : Controller
{
    public ActionResult Index(string searchTerm)
    {
        IEnumerable<Order> orders;

        if (!string.IsNullOrEmpty(searchTerm))
        {
            if (int.TryParse(searchTerm, out int orderId))
            {
                var param = new DynamicParameters();
                param.Add("@OrderId", orderId);

                orders = DP.Listeleme<Order>("sp_SearchOrdersByOrderId", param);
            }
            else
            {
                orders = new List<Order>();
            }
        }
        else
        {
            orders = DP.Listeleme<Order>("sp_GetOrders");
        }

        return View(orders);
    }
    public ActionResult CreateOrder()
    {
        var users = DP.Listeleme<User>("sp_GetUsers");
        ViewBag.Users = new SelectList(users, "UserId", "UserName");
        return View();
    }
    [HttpPost]
    public ActionResult CreateOrder(Order o)
    {
        if (!ModelState.IsValid)
        {
            var users = DP.Listeleme<User>("sp_GetUsers");
            ViewBag.Users = new SelectList(users, "UserId", "UserName");
            return View(o);
        }
        else
        {

            DynamicParameters param = new DynamicParameters();
            param.Add("@UserId", o.UserId);
            param.Add("@OrderDate", o.OrderDate);
            param.Add("@TotalAmount", o.TotalAmount);
            DP.ExecuteReturn("sp_CreateOrder", param);
            TempData["SuccessMessage"] = "Sipariş başarıyla oluşturuldu.";
            return RedirectToAction("Index");
        }
    }
    public ActionResult EditOrder(int id)
    {
        var param = new DynamicParameters();
        param.Add("@OrderId", id);
        var order = DP.Get<Order>("sp_GetOrderById", param);
        if (order == null)
            return NotFound();

        var users = DP.Listeleme<User>("sp_GetUsers");
        ViewBag.Users = new SelectList(users, "UserId", "UserName", order.UserId);
        return View(order);
    }
    [HttpPost]
    [ValidateAntiForgeryToken]
    public ActionResult EditOrder(Order o)
    {
        if (!ModelState.IsValid)
        {
            var users = DP.Listeleme<User>("sp_GetUsers");
            ViewBag.Users = new SelectList(users, "UserId", "UserName", o.UserId);
            return View(o);
        }

        try
        {
            var param = new DynamicParameters();
            param.Add("@OrderId", o.OrderId);
            param.Add("@UserId", o.UserId);
            param.Add("@OrderDate", o.OrderDate);
            param.Add("@TotalAmount", o.TotalAmount);

            DP.ExecuteReturn("sp_UpdateOrder", param);
            TempData["SuccessMessage"] = "Sipariş başarıyla güncellendi.";
            return RedirectToAction("Index");
        }
        catch (Exception)
        {
            ModelState.AddModelError("", "Sipariş güncellenirken hata oluştu.");
            var users = DP.Listeleme<User>("sp_GetUsers");
            ViewBag.Users = new SelectList(users, "UserId", "UserName", o.UserId);
            return View(o);
        }
    }
    [HttpPost]
    public ActionResult DeleteOrder(int id)
    {
        var param = new DynamicParameters();
        param.Add("@OrderId", id);

        try
        {
            DP.ExecuteReturn("sp_DeleteOrder", param);
            TempData["SuccessMessage"] = "Sipariş başarıyla silindi.";
        }
        catch (Exception)
        {
            TempData["ErrorMessage"] = "Sipariş silinirken hata oluştu.";
        }

        return RedirectToAction("Index");
    }
    public ActionResult OrdersByDate()
    {
        ViewBag.StartDate = null;
        ViewBag.EndDate = null;
        return View();
    }

    [HttpPost]
    public ActionResult OrdersByDate(DateTime startDate, DateTime endDate)
    {
        var param = new DynamicParameters();
        param.Add("@StartDate", startDate);
        param.Add("@EndDate", endDate);

        var orders = DP.Listeleme<Order>("sp_GetOrdersByDateRange", param);
        ViewBag.StartDate = startDate.ToString("yyyy-MM-dd");
        ViewBag.EndDate = endDate.ToString("yyyy-MM-dd");

        return View(orders);
    }
    [HttpGet]
    public ActionResult SortByAmount()
    {
        var param = new DynamicParameters();
        param.Add("@SortDirection", "ASC");
        ViewBag.CurrentSort = "ASC";
        var orders = DP.Listeleme<Order>("sp_SortOrdersByAmount", param);
        return View(orders);
    }

    [HttpPost]
    public ActionResult SortByAmount(string sortDirection)
    {
        if (string.IsNullOrEmpty(sortDirection))
            sortDirection = "ASC";

        var param = new DynamicParameters();
        param.Add("@SortDirection", sortDirection);
        ViewBag.CurrentSort = sortDirection;
        var orders = DP.Listeleme<Order>("sp_SortOrdersByAmount", param);
        return View(orders);
    }

    public ActionResult PastOrders()
    {
        var orders = DP.Listeleme<Order>("sp_GetPastOrders");

        if (orders == null || !orders.Any())
        {
            TempData["InfoMessage"] = "Geçmiş sipariş bulunamadı.";
        }
        else
        {
            TempData["InfoMessage"] = "Geçmiş siparişler listeleniyor.";
        }

        return View("Index", orders);
    }

    public ActionResult FutureOrders()
    {
        var orders = DP.Listeleme<Order>("sp_GetFutureOrders");

        if (orders == null || !orders.Any())
        {
            TempData["InfoMessage"] = "Gelecek sipariş bulunamadı.";
        }
        else
        {
            TempData["InfoMessage"] = "Gelecek siparişler listeleniyor.";
        }

        return View("Index", orders);
    }



}

Dapeda/Controllers/ProductController.cs
using System;
using System.Data.SqlClient;
using Dapeda.Models;
using Dapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Dapeda.Controllers
{
    public class ProductController : Controller
    {
        public ActionResult Index(string searchTerm)
        {
            IEnumerable<Product> urunler;

            bool isSearchTermPresent = Request.Query.ContainsKey("searchTerm");

            if (string.IsNullOrWhiteSpace(searchTerm) && isSearchTermPresent)
            {
                ViewBag.Mesaj = "Lütfen arama için bir ürün adı giriniz.";
            }

            if (string.IsNullOrWhiteSpace(searchTerm))
            {
                urunler = DP.Listeleme<Product>("sp_GetProducts");
            }
            else
            {
                var parameters = new DynamicParameters();
                parameters.Add("@SearchTerm", searchTerm);

                urunler = DP.Listeleme<Product>("sp_SearchProductsByName", parameters);
            }

            return View(urunler);
        }




        public ActionResult AddProduct()
        {
            var categories = DP.Listeleme<Category>("sp_GetCategori");
            ViewBag.Categories = new SelectList(categories, "CategoryId", "CategoryName");
            return View();
        }

        [HttpPost]
        public ActionResult AddProduct(Product p)
        {
            DynamicParameters param = new DynamicParameters();
            param.Add("@ProductName", p.ProductName);
            param.Add("@Price", p.Price);
            param.Add("@Stock", p.Stock);
            param.Add("@CategoryId", p.CategoryId);

            DP.ExecuteReturn("sp_AddProduct", param);

            return RedirectToAction("Index");
        }
        public ActionResult DeleteProduct(int id)
        {
            DynamicParameters param = new DynamicParameters();
            param.Add("@ProductId", id);

            DP.ExecuteReturn("sp_DeleteProduct", param);
            return RedirectToAction("Index");
        }
        public ActionResult EditProduct(int id)
        {
            DynamicParameters param = new DynamicParameters();
            param.Add("@ProductId", id);
            var product = DP.GetSingle<Product>("sp_GetProductById", param);


            var categories = DP.Listeleme<Category>("sp_GetCategori");
            ViewBag.Categories = new SelectList(categories, "CategoryId", "CategoryName");

            return View(product);
        }

        [HttpPost]
        public ActionResult EditProduct(Product p)
        {
            DynamicParameters param = new DynamicParameters();
            param.Add("@ProductId", p.ProductId);
            param.Add("@ProductName", p.ProductName);
            param.Add("@Price", p.Price);
            param.Add("@Stock", p.Stock);
            param.Add("@CategoryId", p.CategoryId);

            DP.ExecuteReturn("sp_UpdateProduct", param);

            return RedirectToAction("Index");
        }


        public ActionResult ProductWithCategory()
        {
            var products = DP.Listeleme<ProductWithCategory>("sp_GetProducts").ToList();
            return View(products);
        }


        public ActionResult GetProductReport()
        {
            var products = DP.Listeleme<ProductReport>("sp_GetProductReport").ToList();
            return View(products);
        }

        public IActionResult SortedProducts(string sortBy, string sortDirection = "ASC")
        {
            IEnumerable<Product> products;

            if (sortBy == "price")
                products = GetProductsSortedByPrice(sortDirection);
            else if (sortBy == "stock")
                products = GetProductsSortedByStock(sortDirection);
            else
                products = DP.Listeleme<Product>("sp_GetProducts");

            return View("ProductList", products); // ProductList.cshtml ya da ürün listeleme view dosyanın adı
        }
        public IEnumerable<Product> GetProductsSortedByPrice(string sortDirection)
        {
            var param = new DynamicParameters();
            param.Add("@SortDirection", sortDirection);

            return DP.Listeleme<Product>("sp_SortProductsByPrice", param);
        }

        public IEnumerable<Product> GetProductsSortedByStock(string sortDirection)
        {
            var param = new DynamicParameters();
            param.Add("@SortDirection", sortDirection);

            return DP.Listeleme<Product>("sp_SortProductsByStock", param);
        }


        public IActionResult CategoryPriceReport()
        {
            var model = GetAveragePriceByCategory();
            return View(model);
        }

        public IEnumerable<CategoryPriceSummary> GetAveragePriceByCategory()
        {
            return DP.Listeleme<CategoryPriceSummary>("sp_GetAveragePriceByCategory");
        }


        public Product GetProductWithMaxStock()
        {
            return DP.GetSingle<Product>("sp_GetProductWithMaxStock");
        }

        public Product GetProductWithMinStock()
        {
            return DP.GetSingle<Product>("sp_GetProductWithMinStock");
        }

        public Product GetProductWithMaxPrice()
        {
            return DP.GetSingle<Product>("sp_GetProductWithMaxPrice");
        }

        public Product GetProductWithMinPrice()
        {
            return DP.GetSingle<Product>("sp_GetProductWithMinPrice");
        }

        public IActionResult ProductWithMaxStock()
        {
            var product = GetProductWithMaxStock();
            return View(product); // Tek ürün view’ı için
        }

        public IActionResult ProductWithMinStock()
        {
            var product = GetProductWithMinStock();
            return View("ProductDetail", GetProductWithMinStock());
        }

        public IActionResult ProductWithMaxPrice()
        {
            var product = GetProductWithMaxPrice();
            return View("ProductDetail", product);
        }

        public IActionResult ProductWithMinPrice()
        {
            var product = GetProductWithMinPrice();
            return View("ProductDetail", GetProductWithMinPrice());
        }


        public IActionResult OutOfStockProducts()
        {
            var products = DP.Listeleme<Product>("sp_GetOutOfStockProducts");
            return View(products); // Çoklu ürün listesi view’ı
        }

        // Belirli stok seviyesinin altındaki ürünleri getirir
        public IActionResult ProductsBelowStock(int threshold)
        {
            var param = new DynamicParameters();
            param.Add("@Threshold", threshold);

            var products = DP.Listeleme<Product>("sp_GetProductsBelowStock", param);
            return View(products); // Çoklu ürün listesi view’ı
        }



    }
}

Dapeda/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>@ViewData["Title"] - MARKET</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Dapeda.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css" />
    <style>
        header nav.navbar {
            position: fixed;
            top: 0;
            left: 0;
            right: 0;
            z-index: 1030; 
            background-color: #ffffffcc; 
            backdrop-filter: saturate(180%) blur(10px);
            transition: background-color 0.3s ease;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        }
        footer .social-icons a {
            color: #495057;
            margin-right: 15px;
            font-size: 1.3rem;
            transition: color 0.3s ease;
        }
            footer .social-icons a:hover {
                color: #0d6efd;
            }
        footer.footer {
            padding: 20px 0;
            background-color: #ffffffcc;
            margin-top: 40px;
        }
        body {
            margin: 0;
            padding: 0;
            font-family: 'Segoe UI', sans-serif;
            background: linear-gradient(to right, #4facfe, #00f2fe);
            height: 100vh;
            display: flex;
            align-items: center;
            justify-content: center;
            position: relative; /* Yeni eklenen ::before için gerekli */
            overflow: hidden;
        }
        .login-container {
            background-color: white;
            padding: 40px 30px;
            border-radius: 12px;
            box-shadow: 0 10px 25px rgba(0, 0, 0, 0.2);
            width: 100%;
            max-width: 400px;
            z-index: 1;
            position: relative;
        }
     
        .container {
            position: relative;
            z-index: 10;
        }
    </style>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-light border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand fw-bold" asp-area="" asp-controller="Home" asp-action="Index">Dapeda</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-sm-0">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Product" asp-action="Index">Products</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Category" asp-action="Index">Categories</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Order" asp-action="Index">Orders</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="OrderItem" asp-action="Index">OrderItems</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Account" asp-action="Index">Users</a>
                        </li>
                    </ul>
                    <div class="d-flex align-items-center ms-auto">
                        <a href="@Url.Action("Index", "Home")" title="Admin Panel" class="d-inline-block me-3">
                        </a>
                        <span class="fw-bold fs-5 text-dark me-3">Welcome Admin!</span>
                        <ul class="navbar-nav me-auto mb-2 mb-sm-0">
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Account" asp-action="Login">Logout</a>
                            </li>
                        </ul>
                    </div>

                </div>

            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container d-flex flex-column flex-md-row justify-content-between align-items-center">
            <div>
                &copy; 2025 - Dapeda - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            </div>
            <div class="social-icons mt-2 mt-md-0">
                <a href="https://www.facebook.com" target="_blank" rel="noopener" title="Facebook"><i class="bi bi-facebook"></i></a>
                <a href="https://twitter.com" target="_blank" rel="noopener" title="Twitter"><i class="bi bi-twitter"></i></a>
                <a href="https://www.linkedin.com" target="_blank" rel="noopener" title="LinkedIn"><i class="bi bi-linkedin"></i></a>
                <a href="https://www.instagram.com" target="_blank" rel="noopener" title="Instagram"><i class="bi bi-instagram"></i></a>
            </div>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>